"""delete user nickname

Revision ID: 0bdc208f404a
Revises: 4eaf63d7d355
Create Date: 2025-09-21 16:51:41.055806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdc208f404a'
down_revision: Union[str, Sequence[str], None] = '4eaf63d7d355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tb', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tb', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
